<a href="https://colab.research.google.com/github/shivani14012004/course-of-python/blob/main/DataScience_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science Operations

In [9]:
path='/content/CO2 Emissions_Canada.csv'

In [10]:
#loading the dataset

import pandas as pd

c=pd.read_csv(path)
c.head(2)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221

In [11]:
c.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

#Filter based selection/conditonal selection

In [12]:
c[:2]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221

In [14]:
c['Make'].unique()

array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FIAT',
       'FORD', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI', 'JAGUAR', 'JEEP',
       'KIA', 'LAMBORGHINI', 'LAND ROVER', 'LEXUS', 'LINCOLN', 'MASERATI',
       'MAZDA', 'MERCEDES-BENZ', 'MINI', 'MITSUBISHI', 'NISSAN',
       'PORSCHE', 'RAM', 'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT', 'SUBARU',
       'TOYOTA', 'VOLKSWAGEN', 'VOLVO', 'GENESIS', 'BUGATTI'],
      dtype=object)

In [15]:
#Select only  records of BMW
#c.query("expression")

c.query("Make=='BMW'")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
76,BMW,320i,COMPACT,2.0,4,A8,Z,10.0,6.5,8.4,34,193
77,BMW,320i,COMPACT,2.0,4,M6,Z,10.4,6.7,8.7,32,200
78,BMW,320i xDRIVE,COMPACT,2.0,4,A8,Z,10.2,7.0,8.8,32,202
79,BMW,328d xDRIVE,COMPACT,2.0,4,A8,D,7.6,5.5,6.7,42,181
80,BMW,328d xDRIVE TOURING,STATION WAGON - SMALL,2.0,4,A8,D,7.6,5.5,6.7,42,181
...,...,...,...,...,...,...,...,...,...,...,...,...
6635,BMW,X7 xDrive40i,SUV - STANDARD,3.0,6,AS8,Z,12.0,9.4,10.8,26,254
6636,BMW,X7 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6637,BMW,X7 M50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6638,BMW,Z4 sDrive30i,TWO-SEATER,2.0,4,AS8,Z,9.5,7.4,8.5,33,200
6639,BMW,Z4 M40i,TWO-SEATER,3.0,6,AS8,Z,10.3,8.0,9.3,30,216

In [16]:
c.query("Make=='BMW' and Cylinders>6")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
103,BMW,550i xDRIVE,MID-SIZE,4.4,8,A8,Z,14.4,9.6,12.2,23,281
104,BMW,550i xDRIVE GRAN TURISMO,FULL-SIZE,4.4,8,A8,Z,15.0,9.8,12.7,22,292
106,BMW,650i xDRIVE CABRIOLET,SUBCOMPACT,4.4,8,A8,Z,15.0,9.8,12.7,22,292
107,BMW,650i xDRIVE COUPE,COMPACT,4.4,8,A8,Z,14.4,9.6,12.2,23,281
108,BMW,650i xDRIVE GRAN COUPE,COMPACT,4.4,8,A8,Z,15.0,9.8,12.7,22,292
...,...,...,...,...,...,...,...,...,...,...,...,...
6631,BMW,X5 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6632,BMW,X5 M50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6634,BMW,X6 M50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6636,BMW,X7 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6637,BMW,X7 M50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318

In [17]:
c.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

In [18]:
c['Engine Size(L)'].unique()

array([2. , 2.4, 1.5, 3.5, 3.7, 1.8, 5.9, 4.7, 3. , 4. , 6.3, 4.2, 5.2,
       6. , 6.8, 4.4, 3.6, 1.4, 2.5, 6.2, 4.3, 5.3, 4.8, 1.2, 5.7, 6.4,
       4.6, 5.4, 1.6, 5. , 1. , 5.8, 3.8, 3.3, 5.6, 3.2, 6.5, 5.5, 2.1,
       3.4, 2.7, 6.6, 6.7, 1.3, 8.4, 2.3, 2.8, 0.9, 2.9, 8. , 2.2])

In [19]:
c.query("Make=='BMW' and `Engine Size(L)`>6")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
3436,BMW,M760i xDRIVE,FULL-SIZE,6.6,12,AS8,Z,17.7,11.9,15.1,19,355
4495,BMW,M760i xDRIVE,FULL-SIZE,6.6,12,AS8,Z,17.7,11.9,15.1,19,355
5559,BMW,M760Li xDrive,FULL-SIZE,6.6,12,AS8,Z,17.7,11.9,15.1,19,355
6609,BMW,M760i xDrive Sedan,FULL-SIZE,6.6,12,AS8,Z,17.8,11.9,15.1,19,354

In [20]:
#Access/Filter data using Indexing
#Boolean Indexing

c[c['Vehicle Class'] =='FULL-SIZE']

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
34,AUDI,A8L,FULL-SIZE,3.0,6,AS8,Z,13.1,8.8,11.2,25,258
35,AUDI,A8L,FULL-SIZE,4.0,8,AS8,Z,14.7,9.7,12.5,23,288
36,AUDI,A8L,FULL-SIZE,6.3,12,AS8,Z,18.7,11.5,15.5,18,363
37,AUDI,A8L TDI (modified),FULL-SIZE,3.0,6,AS8,D,9.8,6.5,8.4,34,224
84,BMW,328i xDRIVE GRAN TURISMO,FULL-SIZE,2.0,4,A8,Z,10.6,7.2,9.1,31,209
...,...,...,...,...,...,...,...,...,...,...,...,...
7290,ROLLS-ROYCE,Phantom,FULL-SIZE,6.7,12,AS8,Z,20.0,11.8,16.3,17,382
7291,ROLLS-ROYCE,Phantom EWB,FULL-SIZE,6.7,12,AS8,Z,20.0,11.8,16.3,17,382
7304,SUBARU,Legacy AWD,FULL-SIZE,2.4,4,AV8,X,9.9,7.3,8.7,32,205
7305,SUBARU,Legacy AWD,FULL-SIZE,2.5,4,AV8,X,8.8,6.7,7.9,36,185
7360,VOLKSWAGEN,Arteon 4MOTION,FULL-SIZE,2.0,4,AS8,Z,11.5,8.2,10.0,28,234

In [21]:
c[:1]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196

In [22]:
c['Make']=='ACURA'

0        True
1        True
2        True
3        True
4        True
        ...
7380    False
7381    False
7382    False
7383    False
7384    False
Name: Make, Length: 7385, dtype: bool

In [23]:
c[c['Make']=='ACURA']

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
6508,ACURA,RDX AWD A-SPEC,SUV - SMALL,2.0,4,AS10,Z,11.3,9.1,10.3,27,241
6509,ACURA,RLX Hybrid,MID-SIZE,3.5,6,AM7,Z,8.4,8.2,8.4,34,196
6510,ACURA,TLX A-SPEC,COMPACT,2.4,4,AM8,Z,10.2,7.4,8.9,32,209
6511,ACURA,TLX SH-AWD,COMPACT,3.5,6,AS9,Z,11.4,7.7,9.8,29,228
6512,ACURA,TLX SH-AWD A-SPEC/Limited Edition,COMPACT,3.5,6,AS9,Z,12.0,8.2,10.3,27,240

In [24]:
#Use bitwise & operator as we have multiple True False comparisons
#Logical and wont work here as it is onlyfor single comparison
 c[(c['Make']=='ACURA') & (c['Cylinders']==6)]

IndentationError: unexpected indent (1121271400.py, line 3)

#Groupby operations

In [25]:
c[:1]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196

In [26]:
list(c.groupby(['Make']))

[(('ACURA',),
         Make                              Model Vehicle Class  Engine Size(L)  \
  0     ACURA                                ILX       COMPACT             2.0
  1     ACURA                                ILX       COMPACT             2.4
  2     ACURA                         ILX HYBRID       COMPACT             1.5
  3     ACURA                            MDX 4WD   SUV - SMALL             3.5
  4     ACURA                            RDX AWD   SUV - SMALL             3.5
  ...     ...                                ...           ...             ...
  6508  ACURA                     RDX AWD A-SPEC   SUV - SMALL             2.0
  6509  ACURA                         RLX Hybrid      MID-SIZE             3.5
  6510  ACURA                         TLX A-SPEC       COMPACT             2.4
  6511  ACURA                         TLX SH-AWD       COMPACT             3.5
  6512  ACURA  TLX SH-AWD A-SPEC/Limited Edition       COMPACT             3.5

        Cylinders Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
  0             4          AS5         Z                               9.9
  1             4           M6         Z                              11.2
  2             4          AV7         Z                               6.0
  3             6          AS6         Z                              12.7
  4             6          AS6         Z                              12.1
  ...         ...          ...       ...                               ...
  6508          4         AS10         Z                              11.3
  6509          6          AM7         Z                               8.4
  6510          4          AM8         Z                              10.2
  6511          6          AS9         Z                              11.4
  6512          6          AS9         Z                              12.0

        Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
  0                                 6.7                               8.5
  1                                 7.7                               9.6
  2                                 5.8                               5.9
  3                                 9.1                              11.1
  4                                 8.7                              10.6
  ...                               ...                               ...
  6508                              9.1                              10.3
  6509                              8.2                               8.4
  6510                              7.4                               8.9
  6511                              7.7                               9.8
  6512                              8.2                              10.3

        Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
  0                              33                  196
  1                              29                  221
  2                              48                  136
  3                              25                  255
  4                              27                  244
  ...                           ...                  ...
  6508                           27                  241
  6509                           34                  196
  6510                           32                  209
  6511                           29                  228
  6512                           27                  240

  [72 rows x 12 columns]),
 (('ALFA ROMEO',),
              Make                     Model Vehicle Class  Engine Size(L)  \
  12    ALFA ROMEO                        4C    TWO-SEATER             1.8
  1081  ALFA ROMEO                        4C    TWO-SEATER             1.8
  2211  ALFA ROMEO                        4C    TWO-SEATER             1.8
  3322  ALFA ROMEO                        4C    TWO-SEATER             1.8
  3323  ALFA ROMEO                 4C SPIDER    TWO-SEATER             1.8
  3324  ALFA ROMEO                    GIULIA      MID-SIZE             2.0
  3325  ALFA ROMEO                GIULIA AWD      MID-SIZE             2.0
  3326  ALFA ROMEO       GIULIA QUADRIFOGLIO      MID-SIZE             2.9
  4382  ALFA ROMEO                  4C COUPE    TWO-SEATER             1.8
  4383  ALFA ROMEO                 4C SPIDER    TWO-SEATER             1.8
  4384  ALFA ROMEO                    GIULIA      MID-SIZE             2.0
  4385  ALFA ROMEO                GIULIA AWD      MID-SIZE             2.0
  4386  ALFA ROMEO       GIULIA QUADRIFOGLIO      MID-SIZE             2.9
  4387  ALFA ROMEO               STELVIO AWD   SUV - SMALL             2.0
  4388  ALFA ROMEO      STELVIO QUADRIFOGLIO   SUV - SMALL             2.9
  5466  ALFA ROMEO                  4C Coupe    TWO-SEATER             1.8
  5467  ALFA ROMEO                 4C Spider    TWO-SEATER             1.8
  5468  ALFA ROMEO                    Giulia      MID-SIZE             2.0
  5469  ALFA ROMEO                Giulia AWD      MID-SIZE             2.0
  5470  ALFA ROMEO       Giulia Quadrifoglio      MID-SIZE             2.9
  5471  ALFA ROMEO                   Stelvio   SUV - SMALL             2.0
  5472  ALFA ROMEO               Stelvio AWD   SUV - SMALL             2.0
  5473  ALFA ROMEO  Stelvio AWD Quadrifoglio   SUV - SMALL             2.9
  6513  ALFA ROMEO                 4C Spider    TWO-SEATER             1.8
  6514  ALFA ROMEO                    Giulia      MID-SIZE             2.0
  6515  ALFA ROMEO                Giulia AWD      MID-SIZE             2.0
  6516  ALFA ROMEO       Giulia Quadrifoglio      MID-SIZE             2.9
  6517  ALFA ROMEO                   Stelvio   SUV - SMALL             2.0
  6518  ALFA ROMEO               Stelvio AWD   SUV - SMALL             2.0
  6519  ALFA ROMEO  Stelvio AWD Quadrifoglio   SUV - SMALL             2.9

        Cylinders Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
  12            4          AM6         Z                               9.7
  1081          4          AM6         Z                               9.7
  2211          4          AM6         Z                               9.7
  3322          4          AM6         Z                               9.7
  3323          4          AM6         Z                               9.7
  3324          4           A8         Z                              10.0
  3325          4           A8         Z                              10.5
  3326          6           A8         Z                              13.8
  4382          4          AM6         Z                               9.7
  4383          4          AM6         Z                               9.7
  4384          4           A8         Z                              10.0
  4385          4           A8         Z                              10.5
  4386          6           A8         Z                              13.8
  4387          4           A8         Z                              10.8
  4388          6           A8         Z                              14.1
  5466          4          AM6         Z                               9.7
  5467          4          AM6         Z                               9.7
  5468          4           A8         Z                              10.0
  5469          4           A8         Z                              10.5
  5470          6           A8         Z                              13.8
  5471          4           A8         Z                              10.3
  5472          4           A8         Z                              10.8
  5473          6           A8         Z                              14.1
  6513          4          AM6         Z                               9.7
  6514          4           A8         Z                              10.0
  6515          4           A8         Z                              10.5
  6516          6           A8         Z                              13.5
  6517          4           A8         Z                              10.3
  6518          4           A8         Z                              10.8
  6519          6           A8         Z                              13.9

        Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
  12                                6.9                               8.4
  1081                              6.9                               8.4
  2211                              6.9                               8.4
  3322                              6.9                               8.4
  3323                              6.9                               8.4
  3324                              7.2                               8.7
  3325                              7.7                               9.2
  3326                              9.6                              11.9
  4382                              6.9                               8.4
  4383                              6.9                               8.4
  4384                              7.2                               8.7
  4385                              7.7                               9.2
  4386                              9.6                              11.9
  4387                              8.3                               9.6
  4388                             10.4                              12.4
  5466                              6.9                               8.4
  5467                              6.9                               8.4
  5468                              7.2                               8.7
  5469                              7.7                               9.2
  5470                              9.6                              11.9
  5471                              8.1                               9.3
  5472                              8.3                               9.6
  5473                             10.4                              12.4
  6513                              6.9                               8.4
  6514                              7.2                               8.7
  6515                              7.7                               9.2
  6516                              9.3                              11.6
  6517                              8.1                               9.3
  6518                              8.3                               9.6
  6519                             10.3                              12.3

        Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
  12                             34                  193
  1081                           34                  193
  2211                           34                  197
  3322                           34                  197
  3323                           34                  197
  3324                           32                  205
  3325                           31                  217
  3326                           24                  280
  4382                           34                  197
  4383                           34                  197
  4384                           32                  205
  4385                           31                  217
  4386                           24                  280
  4387                           29                  226
  4388                           23                  292
  5466                           34                  197
  5467                           34                  197
  5468                           32                  205
  5469                           31                  217
  5470                           24                  280
  5471                           30                  218
  5472                           29                  226
  5473                           23                  292
  6513                           34                  197
  6514                           32                  205
  6515                           31                  217
  6516                           24                  271
  6517                           30                  218
  6518                           29                  226
  6519                           23                  288  ),
 (('ASTON MARTIN',),
                Make             Model Vehicle Class  Engine Size(L)  Cylinders  \
  13    ASTON MARTIN               DB9   MINICOMPACT             5.9         12
  14    ASTON MARTIN            RAPIDE    SUBCOMPACT             5.9         12
  15    ASTON MARTIN        V8 VANTAGE    TWO-SEATER             4.7          8
  16    ASTON MARTIN        V8 VANTAGE    TWO-SEATER             4.7          8
  17    ASTON MARTIN      V8 VANTAGE S    TWO-SEATER             4.7          8
  18    ASTON MARTIN      V8 VANTAGE S    TWO-SEATER             4.7          8
  19    ASTON MARTIN          VANQUISH   MINICOMPACT             5.9         12
  1082  ASTON MARTIN               DB9   MINICOMPACT             5.9         12
  1083  ASTON MARTIN          RAPIDE S    SUBCOMPACT             6.0         12
  1084  ASTON MARTIN        V8 VANTAGE    TWO-SEATER             4.7          8
  1085  ASTON MARTIN        V8 VANTAGE    TWO-SEATER             4.7          8
  1086  ASTON MARTIN      V8 VANTAGE S    TWO-SEATER             4.7          8
  1087  ASTON MARTIN      V8 VANTAGE S    TWO-SEATER             4.7          8
  1088  ASTON MARTIN     V12 VANTAGE S    TWO-SEATER             6.0         12
  1089  ASTON MARTIN        VANTAGE GT    TWO-SEATER             4.7          8
  1090  ASTON MARTIN        VANTAGE GT    TWO-SEATER             4.7          8
  1091  ASTON MARTIN          VANQUISH   MINICOMPACT             6.0         12
  2212  ASTON MARTIN            DB9 GT   MINICOMPACT             5.9         12
  2213  ASTON MARTIN          RAPIDE S    SUBCOMPACT             6.0         12
  2214  ASTON MARTIN          VANQUISH   MINICOMPACT             6.0         12
  2215  ASTON MARTIN        V8 VANTAGE    TWO-SEATER             4.7          8
  2216  ASTON MARTIN        V8 VANTAGE    TWO-SEATER             4.7          8
  2217  ASTON MARTIN        VANTAGE GT    TWO-SEATER             4.7          8
  2218  ASTON MARTIN        VANTAGE GT    TWO-SEATER             4.7          8
  2219  ASTON MARTIN      V8 VANTAGE S    TWO-SEATER             4.7          8
  2220  ASTON MARTIN      V8 VANTAGE S    TWO-SEATER             4.7          8
  2221  ASTON MARTIN     V12 VANTAGE S    TWO-SEATER             6.0         12
  3327  ASTON MARTIN          DB11 V12   MINICOMPACT             5.2         12
  3328  ASTON MARTIN          RAPIDE S    SUBCOMPACT             6.0         12
  3329  ASTON MARTIN          VANQUISH   MINICOMPACT             6.0         12
  3330  ASTON MARTIN     V12 VANTAGE S    TWO-SEATER             6.0         12
  3331  ASTON MARTIN     V12 VANTAGE S    TWO-SEATER             6.0         12
  4389  ASTON MARTIN           DB11 V8   MINICOMPACT             4.0          8
  4390  ASTON MARTIN          DB11 V12   MINICOMPACT             5.2         12
  4391  ASTON MARTIN          RAPIDE S    SUBCOMPACT             6.0         12
  4392  ASTON MARTIN          VANQUISH   MINICOMPACT             6.0         12
  5474  ASTON MARTIN           DB11 V8   MINICOMPACT             4.0          8
  5475  ASTON MARTIN          DB11 AMR   MINICOMPACT             5.2         12
  5476  ASTON MARTIN  DBS Superleggera   MINICOMPACT             5.2         12
  5477  ASTON MARTIN        Rapide AMR    SUBCOMPACT             6.0         12
  5478  ASTON MARTIN   Vanquish Zagato   MINICOMPACT             6.0         12
  5479  ASTON MARTIN        Vantage V8    TWO-SEATER             4.0          8
  6520  ASTON MARTIN           DB11 V8   MINICOMPACT             4.0          8
  6521  ASTON MARTIN          DB11 AMR   MINICOMPACT             5.2         12
  6522  ASTON MARTIN  DBS Superleggera   MINICOMPACT             5.2         12
  6523  ASTON MARTIN        Vantage V8    TWO-SEATER             4.0          8
  6524  ASTON MARTIN        Vantage V8    TWO-SEATER             4.0          8

       Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
  13             A6         Z                              18.0
  14             A6         Z                              18.0
  15            AM7         Z                              17.4
  16             M6         Z                              18.1
  17            AM7         Z                              17.4
  18             M6         Z                              18.1
  19             A6         Z                              18.0
  1082           A6         Z                              18.0
  1083           A8         Z                              16.8
  1084          AM7         Z                              17.4
  1085           M6         Z                              18.1
  1086          AM7         Z                              17.4
  1087           M6         Z                              18.1
  1088          AM7         Z                              19.5
  1089          AM7         Z                              17.4
  1090           M6         Z                              18.1
  1091           A8         Z                              17.6
  2212           A6         Z                              18.0
  2213           A8         Z                              16.8
  2214           A8         Z                              17.6
  2215          AM7         Z                              17.4
  2216           M6         Z                              18.1
  2217          AM7         Z                              17.4
  2218           M6         Z                              18.1
  2219          AM7         Z                              17.4
  2220           M6         Z                              18.1
  2221          AM7         Z                              19.5
  3327           A8         Z                              15.5
  3328           A8         Z                              16.7
  3329           A8         Z                              17.5
  3330          AM7         Z                              19.4
  3331           M7         Z                              23.2
  4389           A8         Z                              13.0
  4390           A8         Z                              15.5
  4391           A8         Z                              16.7
  4392           A8         Z                              17.5
  5474           A8         Z                              13.0
  5475           A8         Z                              15.5
  5476           A8         Z                              16.4
  5477           A8         Z                              16.7
  5478           A8         Z                              17.5
  5479           A8         Z                              12.7
  6520           A8         Z                              13.0
  6521           A8         Z                              15.5
  6522           A8         Z                              16.4
  6523           A8         Z                              13.1
  6524           M7         Z                              16.7

        Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
  13                               12.6                              15.6
  14                               12.6                              15.6
  15                               11.3                              14.7
  16                               12.2                              15.4
  17                               11.3                              14.7
  18                               12.2                              15.4
  19                               12.6                              15.6
  1082                             12.6                              15.6
  1083                             10.9                              14.2
  1084                             11.3                              14.7

In [27]:
#fetch a particular group
c.groupby(['Make']).get_group('TOYOTA')

/tmp/ipykernel_1034/69616798.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  c.groupby(['Make']).get_group('TOYOTA')

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
970,TOYOTA,4RUNNER (Part-Time 4WD),SUV - STANDARD,4.0,6,AS5,X,14.3,11.1,12.9,22,297
971,TOYOTA,4RUNNER 4WD,SUV - STANDARD,4.0,6,AS5,X,14.3,11.1,12.9,22,297
972,TOYOTA,AVALON,MID-SIZE,3.5,6,AS6,X,11.3,7.6,9.6,29,221
973,TOYOTA,CAMRY,MID-SIZE,2.5,4,AS6,X,9.5,6.6,8.2,34,189
974,TOYOTA,CAMRY,MID-SIZE,3.5,6,AS6,X,11.1,7.8,9.6,29,221
...,...,...,...,...,...,...,...,...,...,...,...,...
7355,TOYOTA,Tacoma 4WD D-Cab TRD Off-Road/Pro,PICKUP TRUCK - SMALL,3.5,6,M6,X,13.8,11.7,12.9,22,300
7356,TOYOTA,Tundra,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,17.7,13.6,15.9,18,371
7357,TOYOTA,Tundra 4WD,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,18.0,14.2,16.3,17,381
7358,TOYOTA,Yaris,COMPACT,1.5,4,AS6,X,7.3,5.9,6.6,43,155
7359,TOYOTA,Yaris (SIL),COMPACT,1.5,4,M6,X,7.8,6.1,6.9,41,165

In [29]:
c.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

In [31]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
cols=['Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)']
c.groupby(['Make']).get_group('TOYOTA').loc[:,cols].agg([min,max,np.mean])

,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
min,4.30,4.500000,4.400000,17.000000,104.000000
max,19.00,14.200000,16.700000,64.000000,385.000000
mean,10.63,8.449394,9.640606,32.536364,224.424242

In [32]:
c.groupby(['Make'])[cols].agg([min,max,np.mean])

              Fuel Consumption City (L/100 km)                   \
                                           min   max       mean
Make
ACURA                                      6.0  13.4  10.797222
ALFA ROMEO                                 9.7  14.1  10.966667
ASTON MARTIN                              12.7  23.2  17.091489
AUDI                                       7.6  21.2  12.431818
BENTLEY                                   15.1  24.5  18.965217
BMW                                        7.6  18.7  12.611575
BUGATTI                                   26.8  26.8  26.800000
BUICK                                      8.5  19.4  11.802913
CADILLAC                                   9.8  25.7  13.375949
CHEVROLET                                  4.8  30.6  13.772109
CHRYSLER                                  10.2  19.7  14.020455
DODGE                                      8.4  19.9  14.843902
FIAT                                       7.6  11.0   9.227397
FORD                                       5.3  26.7  13.644108
GENESIS                                   11.4  17.2  14.060000
GMC                                        8.5  30.6  15.985976
HONDA                                      4.6  15.2   9.137383
HYUNDAI                                    4.2  17.3  10.016190
INFINITI                                   8.0  17.8  12.391667
JAGUAR                                     7.8  21.3  13.548750
JEEP                                       9.8  20.9  12.270120
KIA                                        4.5  15.7  10.287013
LAMBORGHINI                               16.4  26.6  20.480488
LAND ROVER                                 9.2  25.0  14.475294
LEXUS                                      5.5  19.2  11.694382
LINCOLN                                    5.5  24.5  13.164583
MASERATI                                  14.1  18.2  15.983607
MAZDA                                      7.9  14.3   9.303889
MERCEDES-BENZ                              8.5  24.3  13.657041
MINI                                       8.0  11.5   9.535294
MITSUBISHI                                 6.4  14.2   9.584211
NISSAN                                     7.2  19.7  11.380309
PORSCHE                                   10.5  18.0  12.705053
RAM                                       10.5  20.7  14.968041
ROLLS-ROYCE                               18.7  20.9  20.082000
SCION                                      6.5  10.9   9.709091
SMART                                      6.8   7.5   7.057143
SRT                                       20.0  20.0  20.000000
SUBARU                                     7.9  14.7  10.500714
TOYOTA                                     4.3  19.0  10.630000
VOLKSWAGEN                                 5.6  14.4  10.086294
VOLVO                                      9.6  14.9  11.317742

              Fuel Consumption Hwy (L/100 km)                   \
                                          min   max       mean
Make
ACURA                                     5.8  10.8   8.134722
ALFA ROMEO                                6.9  10.4   7.963333
ASTON MARTIN                              9.4  14.4  11.508511
AUDI                                      5.5  13.8   8.588811
BENTLEY                                   9.1  14.9  11.423913
BMW                                       5.5  13.7   8.719734
BUGATTI                                  16.6  16.6  16.600000
BUICK                                     6.5  13.0   8.418447
CADILLAC                                  6.8  17.8   9.201899
CHEVROLET                                 4.5  20.6   9.775680
CHRYSLER                                  6.4  13.3   9.070455
DODGE                                     5.8  13.3   9.656504
FIAT                                      5.9   8.0   7.079452
FORD                                      5.5  20.5   9.987261
GENESIS                                   8.5  10.5   9.672000
GMC                                       6.0  20.6  11.464024
HONDA                                     4.9  11.3   6.982710
HYUNDAI                                   4.0  10.8   7.596667
INFINITI                                  6.7  12.3   9.075926
JAGUAR                                    5.8  14.1   9.310625
JEEP                                      7.3  13.8   9.208765
KIA                                       4.8  10.6   7.781385
LAMBORGHINI                              11.4  15.8  13.319512
LAND ROVER                                7.8  16.9  10.698824
LEXUS                                     5.2  14.3   8.792135
LINCOLN                                   5.7  18.0   9.518750
MASERATI                                  9.5  12.9  10.742623
MAZDA                                     5.7  10.6   7.097222
MERCEDES-BENZ                             5.7  18.0   9.792840
MINI                                      5.9   8.0   7.129412
MITSUBISHI                                5.3  10.5   7.526316
NISSAN                                    5.8  14.3   8.629730
PORSCHE                                   7.4  12.4   9.143617
RAM                                       7.3  14.7  10.638144
ROLLS-ROYCE                              11.8  13.1  12.562000
SCION                                     5.7   8.6   7.436364
SMART                                     5.7   6.3   6.042857
SRT                                      13.0  13.0  13.000000
SUBARU                                    6.4  11.1   7.949286
TOYOTA                                    4.5  14.2   8.449394
VOLKSWAGEN                                4.9  10.4   7.405076
VOLVO                                     6.6  10.2   8.175806

              Fuel Consumption Comb (L/100 km)                   \
                                           min   max       mean
Make
ACURA                                      5.9  11.6   9.602778
ALFA ROMEO                                 8.4  12.4   9.580000
ASTON MARTIN                              11.2  19.2  14.582979
AUDI                                       6.5  17.8  10.701399
BENTLEY                                   12.4  20.0  15.567391
BMW                                        6.7  16.1  10.864326
BUGATTI                                   22.2  22.2  22.200000
BUICK                                      7.8  16.5  10.272816
CADILLAC                                   8.7  22.1  11.493038
CHEVROLET                                  5.1  26.1  11.973980
CHRYSLER                                   8.5  16.8  11.790909
DODGE                                      7.3  16.7  12.510163
FIAT                                       6.8   9.7   8.267123
FORD                                       5.5  23.9  12.002548
GENESIS                                   10.2  14.2  12.088000
GMC                                        7.4  26.1  13.955793
HONDA                                      4.8  13.4   8.169159
HYUNDAI                                    4.1  14.2   8.927143
INFINITI                                   7.5  15.3  10.900926
JAGUAR                                     6.9  18.1  11.651250
JEEP                                       8.7  17.7  10.901195
KIA                                        4.7  13.4   9.162338
LAMBORGHINI                               14.2  21.7  17.256098
LAND ROVER                                 8.5  21.4  12.771765
LEXUS                                      5.3  16.9  10.359551
LINCOLN                                    5.6  21.6  11.512500
MASERATI                                  12.2  15.3  13.619672
MAZDA                                      6.9  12.7   8.307222
MERCEDES-BENZ                              7.2  21.4  11.917184
MINI                                       7.1   9.9   8.450980
MITSUBISHI                                 5.9  12.5   8.657895
NISSAN                                     6.6  17.3  10.143629
PORSCHE                                    9.2  15.2  11.106649
RAM                                        9.0  18.0  13.022680
ROLLS-ROYCE                               15.6  17.2  16.690000
SCION                                      6.2   9.9   8.677273
SMART                                      6.4   6.9   6.614286
SRT                                       16.9  16.9  16.900000
SUBARU                                     7.5  13.1   9.359286
TOYOTA                                     4.4  16.7   9.640606
VOLKSWAGEN                                 5.3  12.6   8.884264
VOLVO                                      8.3  12.8   9.904032

              Fuel Consumption Comb (mpg)                CO2 Emissions(g/km)  \
                                      min max       mean                 min
Make
ACURA                                  24  48  29.875000                 136
ALFA ROMEO                             23  34  30.133333                 193
ASTON MARTIN                           15  25  19.489362                 264
AUDI                                   16  43  27.206294                 177
BENTLEY                                14  23  18.434783                 291
BMW                                    18  42  26.787476                 181
BUGATTI                                13  13  13.000000                 522
BUICK                                  17  36  28.320388                 182
CADILLAC                               13  32  25.215190                 203
CHEVROLET                              11  55  25.894558                 121
CHRYSLER                               17  33  24.568182                 181
DODGE                                  17  39  23.337398                 168
FIAT                                   29  42  34.369863                 156
FORD                                   12  51  25.213376                 126
GENESIS                                20  28  23.560000                 238
GMC                                    11  38  21.335366                 198
HONDA                                  21  59  35.953271                 110
HYUNDAI                                20  69  33.519048                  96
INFINITI                               18  38  26.574074                 172
JAGUAR                                 16  41  25.037500                 186
JEEP                                   16  32  26.517928                 195
KIA                                    21  60  32.376623                 110
LAMBORGHINI                            13  20  16.634146                 331
LAND ROVER                             13  33  23.247059                 223
LEXUS                                  17  53  28.938202                 124
LINCOLN                                13  50  25.833333                 131
MASERATI                               18  23  20.868852                 286
MAZDA                                  22  41  34.416667                 159
MERCEDES-BENZ                          13  39  24.627685                 128
MINI                                   29  40  33.598039                 163
MITSUBISHI                             23  48  33.684211                 136
NISSAN                                 16  43  29.285714                 152
PORSCHE                                19  31  25.734043                 212
RAM                                    16  31  22.453608                 225
ROLLS-ROYCE                            16  18  17.040000                 359
SCION                                  29  46  33.090909                 143
SMART                                  41  44  42.571429                 147
SRT                                    17  17  17.000000                 389
SUBARU                                 22  38  30.771429                 173
TOYOTA                                 17  64  32.536364                 104
VOLKSWAGEN                             22  53  32.467005                 122
VOLVO                                  22  34  28.790323                 193


               max        mean
Make
ACURA          267  223.652778
ALFA ROMEO     292  224.900000
ASTON MARTIN   450  339.617021
AUDI           409  250.846154
BENTLEY        465  362.934783
BMW            370  254.007590
BUGATTI        522  522.000000
BUICK          323  233.058252
CADILLAC       382  265.854430
CHEVROLET      465  264.346939
CHRYSLER       317  246.170455
DODGE          387  276.361789
FIAT           226  192.246575
FORD           488  260.988854
GENESIS        332  284.840000
GMC            465  299.917683
HONDA          308  190.219626
HYUNDAI        332  208.871429
INFINITI       360  254.064815
JAGUAR         315  267.987500
JEEP           413  250.342629
KIA            318  214.294372
LAMBORGHINI    493  400.780488
LAND ROVER     365  287.647059
LEXUS          395  241.112360
LINCOLN        368  267.302083
MASERATI       360  318.147541
MAZDA          292  193.672222
MERCEDES-BENZ  476  277.386635
MINI           232  196.588235
MITSUBISHI     288  200.505263
NISSAN         398  236.864865
PORSCHE        358  258.941489
RAM            382  292.402062
ROLLS-ROYCE    404  388.480000
SCION          228  200.454545
SMART          157  151.428571
SRT            389  389.000000
SUBARU         301  217.614286
TOYOTA         385  224.424242
VOLKSWAGEN     296  209.335025
VOLVO          294  230.056452